name:calculator.py

on:
  push:
    branches: ["main"]
  pull_request:
    branches:["main"]
  
jobs:
  test:
    runs-on:ubuntu_lateast

    steps:
    name:checkout repo
    use:action/checkout @v4

    name: Set up Python
      uses: actions/setup-python@v4
    
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        python -m unittest discover -s . -p "test_calculator.py"

    
  deploy:
    name: Deploy Job 
    runs-on: ubuntu-latest
    needs: test_job_

    steps:
      - name: Simple Deploy Message
        run: echo "Deploy Job 1 completed successfully!"


    